name: Publish Python Package to PyPI

# This workflow runs when a new release is published on GitHub.
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: 
      name: pypi
      url: https://pypi.org/p/pyrauli

    permissions:
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install build dependencies
      run: pip install build

    - name: Build package
      run: python -m build

    - name: Remove .whl
      run: rm dist/*.whl

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
